name: Workflow con checkout

#on: [push]
on: 
  workflow_dispatch:

jobs:
  probar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el c√≥digo del repo
        uses: actions/checkout@v4

      - name: Ver archivos en el repo
        run: ls -la

      - name: Mensaje final
        run: echo "Todo listo"

