name: Secret Demo

on:
  push:

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar variable normal
        run: echo "Mi nombre es $NAME"
        env:
          NAME: Pepito

      - name: Intentar mostrar secret
        run: echo "El secreto es $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
      
      - name: Longitud
        run: echo "Longitud del secret: ${#MY_SECRET}"

