name: Prueba con secret

on:
  push:

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Variable visible
        run: echo "Mi nombre es $NAME"
        env:
          NAME: Pepito

      - name: Intentar mostrar secret
        run: echo "El secreto es $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Longitud del secret
        run: |
          echo "Longitud del secret:"
          expr length "$MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
